Add camera alvium
DigitalHolography/Holovibes pull request #500
Opened 2024-09-16 13:42 UTC by TitouanGragnic

Camera alvium is working on full resolution 5496x3672 in ~21fps.

2024-09-17 08:10 UTC, ArthurCourselle requested changes
The camera don't quit correctly , missing the stop acquisition function

2024-09-17 08:10 UTC, ArthurCourselle commented on Camera/CameraAlvium/camera_alvium.cc
> +void CameraAlvium::stop_acquisition() {}
Need to implement the function stop_acquisition to correctly stop the camera

2024-09-17 09:53 UTC, ArthurCourselle approved these changes

2024-09-17 09:54 UTC, ArthurCourselle commented
The camera is working and now the stop of acquisition of images are now functionnal + useless code removed. Ready to merge.

2024-09-19 16:10 UTC, alexispinson commented
All test works correctly

2024-09-19 16:10 UTC, merged

2024-09-20 08:05 UTC, Baschtien reviewed
Tout a l'air bien, sauf un petit print-espion oublie.

2024-09-20 08:05 UTC, Baschtien commented on Holovibes/sources/camera_dll.cc
On dirait que un print-espion a ete oublie ; peut-etre le transferer dans l'exception ?

2024-09-20 08:15 UTC, Hpn4 commented on Holovibes/CMakeLists.txt
> +set(VIMBAX_SDK "C:/Program Files/Allied Vision/Vimba X")
Peut être rajouter dans la doc qu'il faut télécharger le SDK et un lien vers le SDK (comme pour le grabber dans le `tutorial.md`)

2024-09-20 08:15 UTC, Hpn4 commented on Camera/CameraAlvium/camera_alvium.cc
> +    name_ = "Alvium-1800-u/2050";
`name_` peut être set directement dans l'initialization list

2024-09-20 08:15 UTC, Hpn4 commented on Camera/CameraAlvium/camera_alvium.cc
> +        }
Les `if` avec une seule ligne n'ont pas besoin de `{` en suivant la coding style

2024-09-20 08:15 UTC, Hpn4 commented on Camera/CameraAlvium/camera_alvium.cc
> +    if (pFrame->GetImage(buf) != VmbErrorType::VmbErrorSuccess)
Peut être utiliser une maccro pour évider la rédondance du test `if(cond != VmbErrorType::VmbErrorSuccess)` du style:
```c++
#define VMB_ERROR(cond) cond != VmbErrorType::VmbErrorSuccess

// Pour finalement avoir
if (VMB_ERROR(cond))
```

2024-09-20 08:25 UTC, TitouanGragnic commented on Camera/CameraAlvium/camera_alvium.cc
> +    unsigned int nBuffers = 1;
maybe increase this value later for processing

2024-09-20 08:34 UTC, Baschtien commented on Holovibes/sources/camera_dll.cc
camera_dll.cc, ligne 21

2024-09-20 08:35 UTC, Baschtien commented on Holovibes/sources/camera_dll.cc
Deso, je croyais que github avait marque la ligne..

2024-09-20 08:45 UTC, TitouanGragnic commented
need to update changelog

2024-09-20 08:48 UTC, TitouanGragnic commented on Camera/Camera/camera.hh
> +        }
en fait ce probleme est fix avec un autre fix qui arrive d'ici peut, du coup le premier if est voué a etre supprimé

2024-09-20 08:51 UTC, TitouanGragnic commented on Camera/CameraAlvium/camera_alvium.cc
> +    name_ = "Alvium-1800-u/2050";
non. (ca compile pas)

2024-09-20 08:53 UTC, TitouanGragnic commented on Camera/CameraAlvium/camera_alvium.cc
> +    name_ = "Alvium-1800-u/2050";
fin c'est possible mais faut refacto toutes les cam