Overhaul AppData handling between DEBUG and RELEASE mode and fix #479
DigitalHolography/Holovibes pull request #511
Opened 2024-09-20 08:32 UTC by GustaveHerve

Allows to build in true DEBUG mode by default and RELEASE mode using the appropriate arguments of dev.py
This makes it possible to have truly distinct AppData locations for both modes, in DEBUG mode we use a local AppData inside the build/bin directory that simulates a user's AppData directory. In RELEASE mode we use the real AppData location of the user (C:\Users\<USER>\AppData\Roaming\Holovibes\<VERSION>).

If we are on RELEASE mode, the program will copy default files of its "reference" folders to the real AppData which will allow them to be used by the user.

This implies that the program is still doing some of the AppData handling at runtime which may not be ideal, but circumventing this is not that easy (we would need to have the installer propagate the files in the real AppData which the CMake build system doesn't allow us to do directly)

There are two duplicates of the get_exe_dir() function used, this should also be fixed (we could have global variable storing the result of get_exe_dir() and accessible everywhere to avoid redudants calls, similar to the "dir" inline variable ).

2024-09-20 08:59 UTC, alexispinson requested changes
Good code just also they may be conflict with simon branch for reducing leaks

2024-09-20 08:59 UTC, alexispinson commented on Holovibes/sources/gui/windows/MainWindow.cc
>      // TODO: move in AppData
Maybe you can remove the todo here.

2024-09-20 08:59 UTC, alexispinson commented on Holovibes/sources/main.cc
> +    // if (std::filesystem::exists(dest))
Delete comments here also maybe

2024-09-20 09:19 UTC, Baschtien approved these changes

2024-09-20 09:28 UTC, Hpn4 reviewed
Il y a deux fois exactement le même get_exe_dir. Peut etre le rajouter à un fichier dans tools ou common. Je trouve que les noms des maccros rendent le code plus compiqué à lire. Peut être simplifier le noms des maccros.

2024-09-20 09:28 UTC, Hpn4 commented on Holovibes/includes/holovibes_config.hh
> +{
C'est exactement la même fonction que dans camera_utils.cc peut être merge les deux dans un seul fichier pour eviter les doublons.

2024-09-23 12:05 UTC, TitouanGragnic commented on Holovibes/sources/gui/windows/MainWindow.cc
> +    // if (!std::filesystem::exists(dest))
deadcode ?

2024-09-23 12:06 UTC, TitouanGragnic commented on Holovibes/sources/gui/windows/MainWindow.cc
> +    // if (!std::filesystem::exists(dest))
fix

2024-09-23 12:08 UTC, merged