Auto detection camera euresys
DigitalHolography/Holovibes pull request #626
Opened 2024-10-18 10:49 UTC by TitouanGragnic

2024-10-18 10:54 UTC, alexispinson requested changes

2024-10-18 10:54 UTC, alexispinson commented on Holovibes/includes/enum/enum_camera_kind.hh
> +    AutoDetectionPhantom,
add comments. People before you were good people, they commented but you arrived and ruined everything

2024-10-18 11:00 UTC, alexispinson approved these changes

2024-10-18 11:01 UTC, Baschtien approved these changes

2024-10-18 11:01 UTC, alexispinson approved these changes

2024-10-21 07:47 UTC, GustaveHerve approved these changes

2024-10-21 07:48 UTC, merged