Add bwareafilt
DigitalHolography/Holovibes pull request #664
Opened 2024-11-06 13:14 UTC by TitouanGragnic

<!> not merge into dev 

add bw area filter into analysis.cc

2024-11-07 08:53 UTC, Hpn4 commented on Holovibes/assets/ui/mainwindow.ui
Maybe delete the double checkbox ?

2024-11-07 09:34 UTC, Baschtien approved these changes

2024-11-07 09:35 UTC, Hpn4 commented on Holovibes/cuda_includes/bw_area_filter.cuh
> +                             size_t* linked_d,
Maybe use a uint instead since the max value will be frame_res.
Also outputs buffer should be before inputs buffer

2024-11-07 09:35 UTC, Hpn4 commented on Holovibes/cuda_includes/bw_area_filter.cuh
> +void get_n_max_index(size_t* labels_size_d, size_t nb_label, size_t* labels_max_d, size_t n, const cudaStream_t stream);
No doc ?

2024-11-07 09:35 UTC, Hpn4 commented on Holovibes/cuda_includes/bw_area_filter.cuh
> + * \brief transforme labels_sizes_d to is_keep_d
No 'e' at the end of transform and maybe explain briefly how it does that

2024-11-07 09:35 UTC, Hpn4 commented on Holovibes/cuda_includes/bw_area_filter.cuh
> + * \param[in] size Number of labels
Rename to size of `labels_size_d`

2024-11-07 09:35 UTC, Hpn4 commented on Holovibes/cuda_sources/bw_area_filter.cu
> +    cudaDeviceSynchronize();
No need to use cudaDeviceSynchronize when following calculation are done on GPU. It should be used when you need result on CPU side

2024-11-07 12:47 UTC, ArthurCourselle requested changes
Checks the commment, you should catch more errors of your functions and also add more documentation to make the part of code that are a bit tricky more understandable

2024-11-07 12:47 UTC, ArthurCourselle commented on Holovibes/cuda_sources/bw_area_filter.cu
> +                                                       size_t_gpu_);
Maybe change the names (1,2,3,4) to something more explicit to understand the use of each kernel and why you needed 4 separate kernels here.

2024-11-07 12:47 UTC, ArthurCourselle commented on Holovibes/cuda_sources/bw_area_filter.cu
> +__global__ void _get_n_max_index(size_t* labels_size_d, size_t nb_label, size_t* labels_max_d, size_t n)
I see that it is for the kernel, in the software the kernel are usually like this : `get_n_max_index_kernel`. Idk if it is a better way of naming

2024-11-07 12:47 UTC, ArthurCourselle commented on Holovibes/cuda_sources/bw_area_filter.cu
> +    _get_n_max_index<<<1, 1, 0, stream>>>(labels_sizes_d, nb_label, labels_max_d, n);
No parallelisation here ? I see you put 1 block and 1 kernel so what is the usage of the kernel ?

2024-11-07 12:47 UTC, ArthurCourselle commented on Holovibes/cuda_sources/bw_area_filter.cu
> +        image_d[idx] = is_keep_d[label_d[idx]] ? 1.0f : 0.0f;
You could use arithmetic operation : is_keep_d[label_d[idx]] * 1.0f

2024-11-07 12:47 UTC, ArthurCourselle commented on Holovibes/cuda_sources/bw_area_filter.cu
> +    cudaDeviceSynchronize();
There is a cudaXDeviceSynchronize function wrapper that you may want to use here

2024-11-07 12:47 UTC, ArthurCourselle commented on Holovibes/cuda_sources/bw_area_filter.cu
At the end of your kernels CUDA you can call `cudaCheckError` to avoid uncatched errors.

2024-11-07 12:47 UTC, ArthurCourselle commented on Holovibes/sources/compute/analysis.cc
> +    size_t_gpu_.resize(1);
Check that the resize function do not raise an error :
err += !size_t_buffer_1_.resize(frame_res);

        if (err != 0)
            throw std::exception(cudaGetErrorString(cudaGetLastError()));

2024-11-07 12:47 UTC, ArthurCourselle commented on Holovibes/sources/compute/analysis.cc
> +                // shift_corners(image_d, 1, fd_.width, fd_.height, stream_);
Dead code

2024-11-07 12:47 UTC, ArthurCourselle commented on Holovibes/sources/compute/analysis.cc
> +                    cudaXFree(labels_max_d);
Maybe you could malloc in the constructor or in an Env because here you Malloc and Free at each pipe cycle that could affect perfs

2024-11-12 09:03 UTC, Baschtien commented
Warning: the test line that (tries to) load data_n.csv is still in the code! it needs to be removed (maybe merge vessels_mask onto this branch ?)

2024-11-12 10:54 UTC, Baschtien commented
Activating the option freezes the entire application

2024-11-13 08:04 UTC, TitouanGragnic commented
> Activating the option freezes the entire application

it's not my code, it's because some dump guys, like open and close some file each time we touch to the analyses panel.
Fortunately they remove this, but the csv are still in the code, but open just once

2024-11-13 11:03 UTC, Baschtien approved these changes

2024-11-14 11:42 UTC, alexispinson commented on Holovibes/includes/compute/analysis.hh
> +        data_csv_cpu = load_CSV_to_float_array("C:/Users/Rakushka/Documents/Holovibes/vascularPulse.csv");
The path doesn't work on my pc

2024-11-14 11:43 UTC, merged