draft: Api fix
DigitalHolography/Holovibes pull request #666
Opened 2024-11-06 14:52 UTC by Hpn4

2024-11-13 14:43 UTC, Baschtien reviewed
Ima be honest, I didn't understand a lot of what you did, especially what you deleted; but by judging how you tested and how most changes are just moving code, it looks good!

However, a lot of (mostly api) functions that take a boolean input have that input named `checked` instead of something more explicit for the context, like `enabled` for example. Is this following a convention ?

2024-11-13 14:43 UTC, Baschtien commented on Holovibes/sources/gui/windows/panels/view_panel.cc
> +        parent_->notify(); // Make the x and y parameters visible
`nImg` doesn't seem to be used here... Maybe it should be in place of the 0 ?

2024-11-14 10:49 UTC, Hpn4 commented on Holovibes/sources/API.cc
> +    }
It was already here, maybe a physical reason for skipping the first frequency. Ask michael if needed

2024-11-14 11:01 UTC, Baschtien approved these changes

2024-11-25 10:12 UTC, simon-riou approved these changes

2024-11-25 10:12 UTC, simon-riou commented on Holovibes/includes/display_queue.hh
> +     */
thanks for adding comments

2024-11-25 10:12 UTC, simon-riou commented on Holovibes/sources/gui/windows/panels/import_panel.cc
>          // The start index cannot exceed the end index
Good job

2024-11-25 10:35 UTC, ArthurCourselle requested changes
Great, I just requested 2-3 changes but only documentation purpose.

2024-11-25 10:35 UTC, ArthurCourselle commented on Holovibes/includes/API.hh
> +
Can you add some doc please ?

2024-11-25 10:35 UTC, ArthurCourselle commented on Holovibes/includes/gui/windows/AdvancedSettingsWindow.hh
> +     * \param callback the function to call
Please precise [in] or [out]

2024-11-25 10:35 UTC, ArthurCourselle commented on Holovibes/sources/gui/GUI.cc
> +    }
1 line if should not have brackets.

2024-11-25 10:35 UTC, ArthurCourselle commented on Holovibes/sources/gui/GUI.cc
> +std::string getNameFromFilename(const std::string& filename)
Please do like the other doxygen comments in holovibes, use `\` and not `@`

2024-11-25 10:35 UTC, ArthurCourselle commented on Holovibes/sources/gui/windows/panels/export_panel.cc
>      // TODO
What is this TODO ? If not yours or you don't know it's origin please remove it.

2024-11-25 12:58 UTC, ArthurCourselle requested changes

2024-11-25 13:24 UTC, merged