Fix registration
DigitalHolography/Holovibes pull request #710
Opened 2024-12-03 12:33 UTC by ArthurCourselle

Fix the registration to make it work regardless of the fftshift.

2024-12-03 13:58 UTC, TitouanGragnic approved these changes
isok

2024-12-04 09:59 UTC, simon-riou requested changes

2024-12-04 09:59 UTC, simon-riou commented on .vscode/launch.json
>              "stopAtEntry": false,
dont push the launch.json please

2024-12-04 10:13 UTC, ArthurCourselle commented on Holovibes/assets/input_filters/filter_Adimec_24bit.bmp
Yep it is a new filter given by olivier

2024-12-04 10:14 UTC, TitouanGragnic approved these changes

2024-12-04 10:15 UTC, simon-riou approved these changes

2024-12-04 10:18 UTC, merged