Fix otsu
DigitalHolography/Holovibes pull request #712
Opened 2024-12-03 13:26 UTC by TitouanGragnic

<!> not in dev

Compute threashold in CPU is ok and don't lose FPS

2024-12-03 14:51 UTC, ArthurCourselle requested changes

2024-12-03 14:51 UTC, ArthurCourselle commented on Holovibes/sources/analysis/analysis.cc
Please remove all the dead code ... ;(

2024-12-03 14:51 UTC, ArthurCourselle commented on Holovibes/cuda_sources/analysis/otsu.cu
> +        atomicAdd(shared_hist + NUM_BINS, 1);
could you use [] operator instead of +

2024-12-03 14:53 UTC, ArthurCourselle approved these changes

2024-12-04 09:28 UTC, Baschtien commented on Holovibes/cuda_sources/analysis/otsu.cu
>      }
The brackets {} are not needed for the loop anymore.

2024-12-04 09:28 UTC, Baschtien commented on Holovibes/sources/analysis/analysis.cc
Maybe don't comment all the csv code ? It may be easier for the Analysis team to merge that way, idk...

2024-12-04 09:31 UTC, TitouanGragnic commented on Holovibes/sources/analysis/analysis.cc
They comment this part of the code for me, they are going to do the merge don't worry

2024-12-04 09:31 UTC, Baschtien commented on Holovibes/sources/analysis/analysis.cc
Ok!

2024-12-04 10:35 UTC, GustaveHerve approved these changes

2024-12-04 12:06 UTC, merged