fix: choose file when saving
DigitalHolography/Holovibes pull request #726
Opened 2024-12-10 13:28 UTC by Hpn4

Before the file name was not saved when choosing a file

2024-12-10 15:05 UTC, Baschtien approved these changes

2024-12-11 10:13 UTC, ArthurCourselle requested changes

2024-12-11 10:13 UTC, ArthurCourselle commented on Holovibes/includes/tools/tools.hh
> +/*! \brief Preprend a string to a file path and append a number if the file already exists
There is 2 \brief comments.

2024-12-11 10:13 UTC, ArthurCourselle commented on Holovibes/includes/tools/tools.hh
> + *
params in or out

2024-12-11 10:33 UTC, simon-riou approved these changes
very nice good job my man

2024-12-11 12:02 UTC, ArthurCourselle approved these changes

2024-12-11 12:05 UTC, merged