Api
DigitalHolography/Holovibes pull request #741
Opened 2024-12-18 12:34 UTC by Hpn4

2025-01-04 16:02 UTC, Hpn4 commented
Crash:
- [ ] Read file, open a camera (without stoping) then start (without doing camera none)
- [ ] Switching to/from composite in camera mode

2025-01-06 08:49 UTC, alexispinson requested changes

2025-01-06 08:49 UTC, alexispinson commented on Holovibes/sources/cli/cli.cc
>      std::string input_path = opts.input_path.value();
No need to have holovibes::Holovibes& holovibes as a parameter in set_parameters and main_loop

2025-01-06 10:00 UTC, Baschtien reviewed
Looks great!
My comments are mostly suggestions, questions and documentation requests

2025-01-06 10:00 UTC, Baschtien commented on Camera/CameraOpenCV/camera_opencv.cc
> +    apiID_ = cv::CAP_DSHOW; /* autodetect default API */
I trust that this doesn't break anything, right ?

2025-01-06 10:00 UTC, Baschtien commented on Holovibes/includes/api/compute_api.hh
You have added ApiCode as a return type for a number of functions, but no documentation has been provided to explain it. Is it wanted ?
(There are other files where this is true as well)

2025-01-06 10:00 UTC, Baschtien commented on Holovibes/includes/api/information_api.hh
> +     * \return const float
Ah yes, the mystery float
I mean cmon (sorry)

2025-01-06 10:00 UTC, Baschtien commented on Holovibes/includes/core/holovibes.hh
> +    void start_camera_frame_read();
\param is not necessary anymore
Also, the TODO is probably obsolete as well (check issue to make sure)

2025-01-06 10:00 UTC, Baschtien commented on Holovibes/includes/core/pipe.hh
> +                                                          buffers_.gpu_output_queue->get_fd(),
Isn't the pipe itself better suited to host the gpu output queue ? It feels kinda hidden in buffers_ (but its just my opinion)

2025-01-06 10:00 UTC, Baschtien commented on Holovibes/includes/enum/enum_api_code.hh
> +    WRONG_IMG_TYPE,  /*!< The operation could not be performed on this computation mode */
What is the difference between these two api codes ? (they litterally have the same description)

2025-01-06 10:00 UTC, Baschtien commented on Holovibes/sources/api/compute_api.cc
> +        stop();
In theory you don't need the if (as it is done in stop()), but maybe it is (slightly) more optimized this way ?

2025-01-06 10:00 UTC, Baschtien commented on Holovibes/sources/api/compute_api.cc
> +        return ApiCode::OK;
Why shouldn't the code next to this check run if no computation is on ?
If the computation starts next, the changes done by the next lines wouldn't have been applied, would it ? Or is it not important ?

2025-01-06 10:00 UTC, Baschtien commented on Holovibes/sources/api/compute_api.cc
> -        return;
Y u get rid of my beautiful code snif
(seriously, why ? Has the check been moved ?)

2025-01-06 10:00 UTC, Baschtien commented on Holovibes/sources/api/record_api.cc
> +            Holovibes::instance().init_record_queue();
Maybe you could add another function `get_is_computation_started` or something instead of using this one.
For me it feels weird to write 'If it isn't stopped' instead of 'If it is started' (at the very least 'If it isn't started' but whatever)
Just a suggestion tho

2025-01-06 10:00 UTC, Baschtien commented on Holovibes/sources/gui/windows/panels/import_panel.cc
> +
Ok ce sont des includes mais pk ya un espace random ? (sorry)

2025-01-06 10:19 UTC, Hpn4 commented on Camera/CameraOpenCV/camera_opencv.cc
> +    apiID_ = cv::CAP_DSHOW; /* autodetect default API */
It allows the OpenCV camera to be opened multiple times and also fix contrast with it (because it makes auto contrast on it's own)

2025-01-06 10:20 UTC, Baschtien commented on Camera/CameraOpenCV/camera_opencv.cc
> +    apiID_ = cv::CAP_DSHOW; /* autodetect default API */
Ok!

2025-01-06 10:21 UTC, Hpn4 commented on Holovibes/includes/core/holovibes.hh
> +    void start_camera_frame_read();
I check the issue and it seems not obselete maybe check with michael

2025-01-06 10:23 UTC, Hpn4 commented on Holovibes/includes/enum/enum_api_code.hh
> +    WRONG_IMG_TYPE,  /*!< The operation could not be performed on this computation mode */
Typo fixed one is for image type (magnitude, composite...) and other computation mode (raw, compute)

2025-01-06 10:24 UTC, Hpn4 commented on Holovibes/sources/api/compute_api.cc
> +        stop();
Yeah relica of multiple commits of mine

2025-01-06 10:29 UTC, Hpn4 commented on Holovibes/sources/api/compute_api.cc
> +        return ApiCode::OK;
You are right it should be just before calling pipe

2025-01-06 10:35 UTC, Hpn4 commented on Holovibes/sources/api/compute_api.cc
> -        return;
Because moments works with raw compute mode so i don't understand why blocking it ?

2025-01-06 10:36 UTC, Hpn4 commented on Holovibes/sources/gui/windows/panels/import_panel.cc
> +
Separate "parent" header from internal headers

2025-01-06 10:37 UTC, Hpn4 commented on Holovibes/includes/api/compute_api.hh
You mean documentation for each function like which api code is returned or documenting the enum api code ?

2025-01-06 10:38 UTC, Baschtien commented on Holovibes/sources/api/compute_api.cc
> -        return;
It has to do with the way I coded it
The way I saw it, there was only one way to read moments, so I forced the compute mode to be 'Processed' in the UI (and previously in the API, which is this line here).

Maybe take a look at the refresh() function in pipe.cc

2025-01-06 10:38 UTC, Baschtien commented on Holovibes/sources/api/compute_api.cc
> -        return;
I guess what can be done is that raw mode with a moments file completely skips postprocessing steps (as raw mode does right now)

2025-01-06 10:41 UTC, Baschtien commented on Holovibes/includes/api/compute_api.hh
Hmm I see what you mean
I originally wanted doc for each function that returns an API code, but now I see that it would be pretty useless given how self-explanatory most of the codes already are

2025-01-06 10:41 UTC, Baschtien commented on Holovibes/includes/api/compute_api.hh
But maybe at least a \return ?

2025-01-06 10:44 UTC, TitouanGragnic approved these changes

2025-01-06 10:50 UTC, Hpn4 commented on Holovibes/includes/api/compute_api.hh
I added all the possible return type

2025-01-06 10:52 UTC, Hpn4 commented on Holovibes/sources/api/record_api.cc
> +            Holovibes::instance().init_record_queue();
I like to keep the fewest number of function possible

2025-01-06 10:53 UTC, Hpn4 commented on Holovibes/sources/api/compute_api.cc
> -        return;
I found this weird since we cannot be in raw mode but we can open the raw window. So either blocking the two or accepting the two. But i don't see why blocking ? The raw rendering will be the three moments passing one to another like m0, m1, m2, m0...

2025-01-06 10:54 UTC, Hpn4 commented on Holovibes/includes/core/pipe.hh
> +                                                          buffers_.gpu_output_queue->get_fd(),
Since all output queues and buffers are in env it will be weird to only have one external.

2025-01-06 11:42 UTC, Baschtien commented on Holovibes/sources/api/compute_api.cc
> -        return;
I hadn't seen it that way.. Yeah I guess it works if this is the intended behavior !

2025-01-06 11:42 UTC, Baschtien commented on Holovibes/sources/api/record_api.cc
> +            Holovibes::instance().init_record_queue();
K

2025-01-07 07:28 UTC, alexispinson approved these changes

2025-01-07 09:06 UTC, merged